Repository soccer-community-P-C/soccer-community-frontend, pull requests merged in 2024-05, with the labels that each got.

#3 develop 브랜치로 main 브랜치 병합
  .eslintrc.json
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc
  package-lock.json
  package.json
Labels: CHORE

#5 prettier-plugin-tailwindcss 설정
  .prettierrc
  package-lock.json
  package.json
Labels: CHORE

#7 husky로 pre-commit, pre-push 설정
  .husky/pre-commit
  .husky/pre-push
  package-lock.json
  package.json
Labels: CHORE

#9 8 header footer
  .idea/jsLinters/eslint.xml
  .idea/prettier.xml
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/app/result/page.tsx
  src/assets/img/soccerball.png
  src/components/MainFooter/MainFooter.tsx
  src/components/MainHeader/MainHeader.tsx
  src/components/MainHeader/NavLinkItem.tsx
  src/components/MainHeader/NavLinkList.tsx
  src/components/MainHeader/NavSubLinkList.tsx
  tailwind.config.ts
Labels: FEAT

#12 회원가입 페이지 UI 구현
  src/app/signup/page.tsx
  src/components/common/Input.tsx
Labels: FEAT

#14 로그인 페이지 UI 구현
  src/app/login/page.tsx
Labels: FEAT

#15 Feat/#10 match schedule results
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/app/premier/layout.tsx
  src/app/premier/loading.tsx
  src/app/premier/page.tsx
  src/app/premier/rank/page.tsx
  src/app/premier/result/page.tsx
  src/app/result/page.tsx
  src/assets/img/logo/logo_premier.png
  src/components/Common/Button.tsx
  src/components/Common/LinkItem.tsx
  src/components/Common/box-heading.tsx
  src/components/Common/box.tsx
  src/components/Common/contentHeader/contentHeader.tsx
  src/components/Common/contentHeader/leagueTitle.tsx
  src/components/MainHeader/MainHeader.tsx
  src/components/MainHeader/NavLinkItem.tsx
  src/components/MainHeader/NavLinkList.tsx
  src/components/MainHeader/NavSubLinkList.tsx
  src/components/Result/DatePicker.tsx
  src/components/Result/Result.tsx
  src/components/Result/ResultOfGame.tsx
  src/components/Result/ResultOfGameItem.tsx
  src/components/rank/rank.tsx
  src/utils/date-helper.ts
Labels: FEAT

#21 Feat: 순위 페이지 구현, 변수 리팩토링
  src/app/layout.tsx
  src/app/premier/layout.tsx
  src/app/premier/rank/page.tsx
  src/app/premier/result/page.tsx
  src/components/Common/box-heading.tsx
  src/components/Common/content-header/content-header.tsx
  src/components/main-footer/main-footer.tsx
  src/components/main-header/main-header.tsx
  src/components/main-header/nav-link-item.tsx
  src/components/main-header/nav-link-list.tsx
  src/components/main-header/nav-sub-link-list.tsx
  src/components/rank/rank-item.tsx
  src/components/rank/rank-table.tsx
  src/components/result/date-picker.tsx
  src/components/result/result-of-game.tsx
  src/components/result/result.tsx
  src/utils/date-helper.ts
Labels: FEAT, REFACTOR, STYLE
