Repository soccer-community-P-C/soccer-community-frontend, pull requests merged in 2024-06, with the labels that each got.

#24 Feat/#22, 경기별 상세 정보, 라리가 페이지
  src/app/(league)/laliga/board/page.tsx
  src/app/(league)/laliga/page.tsx
  src/app/(league)/laliga/rank/page.tsx
  src/app/(league)/laliga/result/page.tsx
  src/app/(league)/layout.tsx
  src/app/(league)/loading-dots.module.css
  src/app/(league)/loading.tsx
  src/app/(league)/premier/board/page.tsx
  src/app/(league)/premier/page.tsx
  src/app/(league)/premier/rank/page.tsx
  src/app/(league)/premier/result/page.tsx
  src/app/globals.css
  src/app/match/page.tsx
  src/app/premier/loading.tsx
  src/app/premier/page.tsx
  src/components/Common/box-heading.tsx
  src/components/Common/container.tsx
  src/components/Common/content-header/content-header.tsx
  src/components/Common/link-item.tsx
  src/components/Common/linkItem.tsx
  src/components/Common/loading-spinner.tsx
  src/components/main-header/nav-link-list.tsx
  src/components/match/goal-Info.tsx
  src/components/match/match-header.tsx
  src/components/match/match-record-category-item.tsx
  src/components/match/match-record-category.tsx
  src/components/match/match-record-tab.tsx
  src/components/match/match-record.tsx
  src/components/match/match-section.tsx
  src/components/match/mom-vote-best-player.tsx
  src/components/match/mom-vote-player.tsx
  src/components/match/mom-vote.tsx
  src/components/rank/rank-table.tsx
  src/components/result/date-picker.tsx
  src/components/result/result-of-game-item.tsx
  src/components/result/result-of-game.tsx
  src/components/result/result.tsx
  src/utils/date-helper.ts
Labels: FEAT

#25 게시판 UI 구현
  src/app/premier/board/page.tsx
  src/components/board/pagination.tsx
Labels: FEAT

#32 Feat: 경기 일정 API 연결, 경기 세부 결과 선수 스탯
  .gitignore
  next.config.mjs
  src/app/(league)/laliga/board/page.tsx
  src/app/(league)/laliga/page.tsx
  src/app/(league)/laliga/rank/page.tsx
  src/app/(league)/laliga/result/page.tsx
  src/app/(league)/layout.tsx
  src/app/(league)/loading-dots.module.css
  src/app/(league)/loading.tsx
  src/app/(league)/premier/board/page.tsx
  src/app/(league)/premier/page.tsx
  src/app/(league)/premier/player/rank/page.tsx
  src/app/(league)/premier/rank/page.tsx
  src/app/(league)/premier/result/page.tsx
  src/app/globals.css
  src/app/match/page.tsx
  src/app/premier/loading.tsx
  src/app/premier/page.tsx
  src/assets/Chelsea.png
  src/components/Common/box-heading.tsx
  src/components/Common/container.tsx
  src/components/Common/content-header/content-header.tsx
  src/components/Common/link-item.tsx
  src/components/Common/linkItem.tsx
  src/components/Common/loading-spinner.tsx
  src/components/Common/table/table-container.tsx
  src/components/board/pagination.tsx
  src/components/main-header/nav-link-list.tsx
  src/components/match/goal-Info.tsx
  src/components/match/match-header.tsx
  src/components/match/match-record-category-item.tsx
  src/components/match/match-record-category.tsx
  src/components/match/match-record-tab.tsx
  src/components/match/match-record.tsx
  src/components/match/match-section.tsx
  src/components/match/match-select-team-button.tsx
  src/components/match/mom-vote-best-player.tsx
  src/components/match/mom-vote-player.tsx
  src/components/match/mom-vote.tsx
  src/components/player-rank/player-rank-item.tsx
  src/components/player-rank/player-rank-thead.tsx
  src/components/player-rank/player-rank.tsx
  src/components/rank/rank-item.tsx
  src/components/rank/rank-table.tsx
  src/components/result/date-picker.tsx
  src/components/result/result-of-game-item.tsx
  src/components/result/result-of-game.tsx
  src/components/result/result.tsx
  src/utils/date-helper.ts
Labels: FEAT

#34 게시글 작성 페이지 UI 구현
  package-lock.json
  package.json
  src/app/(league)/premier/board/page.tsx
  src/app/(league)/premier/write/page.tsx
  src/components/common/Input.tsx
  src/components/write/editor.tsx
  src/hooks/useInput.ts
Labels: FEAT, REFACTOR

#37 next config 수정
  next.config.mjs
Labels: FIX

#38 Feat/#35 선수 상세 페이지 구현
  src/app/(league)/laliga/player-rank/page.tsx
  src/app/(league)/premier/player-rank/page.tsx
  src/app/page.tsx
  src/app/player/[slug]/page.tsx
  src/assets/img/player_test_img.jpeg
  src/components/Common/content-header/content-header.tsx
  src/components/player/player-info-item.tsx
  src/components/player/player-info.tsx
  src/components/player/player-stat-item.tsx
  src/components/player/player-stat.tsx
  src/components/player/player.tsx
Labels: FEAT
