Repository soccer-community-P-C/soccer-community-frontend, pull requests merged in 2024-07, with the labels that each got.

#42 Fix/#41 fix release
  .eslintrc.json
  .gitignore
  .idea/prettier.xml
  next.config.mjs
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/match/page.tsx
  src/components/common/input.tsx
  src/components/match/match-header.tsx
  src/components/match/match-record.tsx
  src/components/match/match-section.tsx
  src/components/match/match.tsx
  src/components/player/player-stat-item.tsx
  src/components/result/result-of-game-item.tsx
  src/components/result/result-of-game.tsx
  src/components/result/result.tsx
  src/context/result-of-game-context.tsx
  src/hooks/useInput.tsx
  src/hooks/useReactQuery.tsx
  src/hooks/useResultOfGame.tsx
  src/types/result-of-game-type.ts
  src/utils/intance.ts
Labels: FEAT, FIX, RELEASE

#49 Feat/#48 home page
  src/app/globals.css
  src/app/page.tsx
  src/components/board/pagination.tsx
  src/components/common/box-heading.tsx
  src/components/common/table/table-container.tsx
  src/components/common/test.json
  src/components/common/view-all-link-item.tsx
  src/components/home/dropdown.tsx
  src/components/home/laliga-result.tsx
  src/components/home/premier-result.tsx
  src/components/rank/rank-item.tsx
  src/components/rank/rank-table.tsx
  src/components/rank/rank.tsx
  src/components/result/result-of-game-item.tsx
  src/components/result/result-of-game.tsx
  src/utils/intance.ts
Labels: FEAT

#51 Refactor: React Query 구조 변경, types 설정
  src/api/intance.ts
  src/api/league-game/index.ts
  src/api/league-game/league-games.ts
  src/api/league-game/use-get-all-game-list.tsx
  src/api/league-game/use-get-game-by-league-game-id.tsx
  src/api/league-game/use-get-game-list-by-date.tsx
  src/api/league-game/use-get-game-list-by-league-game-id-year-month.tsx
  src/app/layout.tsx
  src/components/home/laliga-result.tsx
  src/components/home/premier-result.tsx
  src/components/react-query-providers.tsx
  src/components/result/result-of-game-item.tsx
  src/components/result/result-of-game.tsx
  src/components/result/result.tsx
  src/context/result-of-game-context.tsx
  src/types/league-games.ts
  src/types/result-of-game-type.ts
Labels: REFACTOR

#54 게시글 조회 UI 구현
  package-lock.json
  package.json
  src/app/(league)/premier/board/[postId]/page.tsx
Labels: FEAT

#56 게시글 작성 기능 구현
  src/api/post/index.ts
  src/api/post/posts.ts
  src/api/post/use-write-post.ts
  src/app/(league)/premier/write/page.tsx
  src/components/write/editor.tsx
  src/hooks/useLeagueName.tsx
  src/types/posts.ts
Labels: FEAT

#57 Feat/#52 homepage UI and league game api
  README.md
  next.config.mjs
  src/api/league-game/league-games.ts
  src/api/league-game/use-get-game-list-by-league-game-id-year-month.tsx
  src/app/(league)/laliga/result/page.tsx
  src/app/(league)/premier/league-game/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/content-header/content-header.tsx
  src/components/home/home-rank.tsx
  src/components/home/laliga-result.tsx
  src/components/home/premier-result.tsx
  src/components/home/rank-tab-list.tsx
  src/components/league-game/calendar.tsx
  src/components/league-game/date-picker.tsx
  src/components/league-game/league-game-content-item.tsx
  src/components/league-game/league-game-content-list.tsx
  src/components/league-game/league-game-content.tsx
  src/components/league-game/league-game.tsx
  src/components/league-game/service/game-list.ts
  src/components/main-header/nav-link-list.tsx
  src/components/match/match-header.tsx
  src/components/match/match-record-tab.tsx
  src/components/match/match-select-team-button.tsx
  src/components/result/result.tsx
  src/constants/league-game-id.ts
  src/context/league-game-content-context.tsx
  src/context/result-of-game-context.tsx
  src/hooks/use-league-game-content.tsx
  src/hooks/useResultOfGame.tsx
  src/types/league-games.ts
  src/utils/date-helper.ts
Labels: FEAT

#60 게시글 삭제 기능 구현
  src/api/post/index.ts
  src/api/post/posts.ts
  src/api/post/use-delete-post.ts
  src/app/(league)/premier/board/[postId]/page.tsx
Labels: FEAT

#61 게시글 리스트 조회 기능 구현
  src/api/post/posts.ts
  src/api/post/use-get-post-list.ts
  src/api/post/use-write-post.ts
  src/app/(league)/premier/board/page.tsx
  src/components/board/pagination.tsx
  src/types/posts.ts
Labels: FEAT

#64 Fix: 빌드 오류 수정
  src/app/(league)/laliga/board/page.tsx
  src/app/(league)/premier/board/page.tsx
  src/app/(league)/premier/write/page.tsx
  src/components/board/pagination.tsx
Labels: FIX

#65 게시글 삭제 후 로직 수정
  src/api/post/use-delete-post.ts
  src/app/(league)/premier/board/page.tsx
  src/components/board/pagination.tsx
Labels: FIX

#67 글 작성 시 빈 값일 때 작성 안되게 수정
  src/app/(league)/premier/write/page.tsx
Labels: FIX
