Repository soccer-community-P-C/soccer-community-frontend, pull requests merged in 2024-09, with the labels that each got.

#133 닉네임 필드 nickname으로 수정
  src/app/profile/page.tsx
  src/types/members.ts
Labels: REFACTOR

#138 Protected Routes 구현
  src/api/auth/use-login.tsx
  src/app/login/page.tsx
  src/app/profile/page.tsx
  src/app/signup/page.tsx
  src/hocs/withAuth.tsx
  src/hocs/withoutAuth.tsx
Labels: FEAT

#141 Feat/#136 경기일정페이지, 모바일 기기 환경에서 팀 선택 드롭다운 셀렉트로 팀 선택 기능 구현
  package-lock.json
  package.json
  src/components/schedule/schedule.tsx
  src/components/schedule/team-list.tsx
  src/components/ui/select.tsx
  src/constants/team-list.ts
Labels: FEAT, FIX

#144 Fix: build 에러 수정
  src/components/schedule/team-list.tsx
  src/hocs/withAuth.tsx
  src/hocs/withoutAuth.tsx
Labels: FIX

#147 Feat/#145 리그별 아이디를 가져와 관련된 api 호출
  src/api/league-game/use-get-game-list-by-league-game-id-year-month.tsx
  src/api/league/leagues.ts
  src/api/league/use-get-all-league.tsx
  src/api/league/use-get-league.tsx
  src/api/league/use-get-team-list.tsx
  src/api/league/use-get-team-rank.tsx
  src/app/page.tsx
  src/components/home/home-rank.tsx
  src/components/home/premier-schedule.tsx
  src/components/player-rank/player-rank.tsx
  src/components/rank/rank-table.tsx
  src/components/rank/rank.tsx
  src/components/schedule/date-picker.tsx
  src/components/schedule/schedule-content-item.tsx
  src/components/schedule/schedule.tsx
  src/components/schedule/team-list.tsx
  src/hooks/useLeagueName.tsx
  src/types/leagues.ts
Labels: FEAT

#149 Revert "Feat/#145 리그별 아이디를 가져와 관련된 api 호출"
  src/api/league-game/use-get-game-list-by-league-game-id-year-month.tsx
  src/api/league/leagues.ts
  src/api/league/use-get-all-league.tsx
  src/api/league/use-get-league.tsx
  src/api/league/use-get-team-list.tsx
  src/api/league/use-get-team-rank.tsx
  src/app/page.tsx
  src/components/home/home-rank.tsx
  src/components/home/premier-schedule.tsx
  src/components/player-rank/player-rank.tsx
  src/components/rank/rank-table.tsx
  src/components/rank/rank.tsx
  src/components/schedule/date-picker.tsx
  src/components/schedule/schedule-content-item.tsx
  src/components/schedule/schedule.tsx
  src/components/schedule/team-list.tsx
  src/hooks/useLeagueName.tsx
  src/types/leagues.ts
Labels: FEAT

#154 Feat/#153 골정보 api 연동및 페이지 오류 수정
  src/components/home/premier-schedule.tsx
  src/components/match/goal-Info.tsx
  src/components/match/match-header.tsx
  src/components/match/match-record.tsx
  src/components/schedule/schedule-content-item.tsx
  src/types/schedules.ts
Labels: FEAT, FIX

#156 Refactor/#155 home page UI
  src/api/league-game/league-games-types.ts
  src/api/league-game/league-games.ts
  src/api/league-game/use-get-game-list-by-date.tsx
  src/components/home/home-rank.tsx
  src/components/home/laliga-schedule.tsx
  src/components/home/premier-schedule.tsx
  src/components/rank/rank.tsx
Labels: REFACTOR

#159 Feat/#146 팀 순위 매치데이별 그래프 구현
  package-lock.json
  package.json
  src/components/common/echart.tsx
  src/components/match/match-header.tsx
  src/components/match/match-record.tsx
  src/components/match/match-select-team-button.tsx
  src/components/match/match.tsx
  src/components/rank/rank-graph.tsx
  src/components/rank/rank.tsx
  src/components/schedule/schedule-content-item.tsx
  src/types/schedules.ts
  src/utils/rank-graph-generate.ts
Labels: CHORE, FEAT, FIX

#161 Feat/#160 경기 일정 페이지 스크롤 기능 구현
  src/app/(league)/premier/schedule/page.tsx
  src/components/schedule/schedule-content-list.tsx
  src/components/schedule/schedule-content.tsx
  src/components/schedule/schedule.tsx
  src/types/schedules.ts
Labels: FEAT

#163 Feat: 구글 로그인 테스트를 위한 테스트 구현
  src/api/auth/auths.ts
  src/api/auth/use-google-login.tsx
  src/app/login/page.tsx
Labels: FEAT

#167 Fix: Link대신 router를 통해 빌드시 미리 라우팅안하게 설정, Todo 작성
  src/app/login/page.tsx
Labels: FIX

#157 게시글 좋아요 기능 구현
  src/api/post/posts.ts
  src/api/post/use-like-post.ts
  src/app/post/[postId]/page.tsx
Labels: FEAT

#172 React Quill 에디터에 link 삭제
  src/components/write/editor.tsx
Labels: FEAT
