Repository soccer-community-P-C/soccer-community-frontend, pull requests merged in 2024-08, with the labels that each got.

#78 게시글 상세 조회 구현
  src/api/post/index.ts
  src/api/post/posts.ts
  src/api/post/use-delete-post.tsx
  src/api/post/use-get-post-list.tsx
  src/api/post/use-get-post.tsx
  src/api/post/use-write-post.tsx
  src/app/(league)/premier/board/[postId]/page.tsx
  src/components/common/loading-spinner.tsx
  src/types/posts.ts
  src/utils/date-helper.ts
Labels: FEAT

#77 Feat: 경기 상세 조회 api 연동 및 팀 리스트 UI 구현
  next.config.mjs
  src/api/league-game/league-games.ts
  src/api/league-game/use-get-all-game-list.tsx
  src/api/league-game/use-get-game-by-league-game-id.tsx
  src/api/league-game/use-get-game-list-by-date.tsx
  src/api/league-game/use-get-game-list-by-league-game-id-year-month.tsx
  src/api/league-game/use-get-game-list-by-team-id.tsx
  src/app/(league)/premier/league-game/page.tsx
  src/app/match/[leagueGameId]/page.tsx
  src/app/match/page.tsx
  src/app/page.tsx
  src/components/common/scroll-button.tsx
  src/components/home/laliga-league-game.tsx
  src/components/home/premier-league-game.tsx
  src/components/league-game/index.ts
  src/components/league-game/league-game-content-item.tsx
  src/components/league-game/league-game-content.tsx
  src/components/league-game/league-game.tsx
  src/components/league-game/team-list.tsx
  src/components/league-game/team-logo.tsx
  src/components/match/match-header.tsx
  src/components/match/match-record-tab.tsx
  src/components/match/match-record.tsx
  src/components/match/match-section.tsx
  src/components/match/match.tsx
  src/types/league-games.ts
  src/utils/date-helper.ts
Labels: FEAT

#81 게시글 댓글 작성 기능 구현
  src/api/comment/comments.ts
  src/api/comment/index.ts
  src/api/comment/use-write-comment.tsx
  src/app/(league)/premier/board/[postId]/page.tsx
  src/hooks/useInput.tsx
Labels: FEAT

#82 Feat/#72 선수 조회 api 연동, 선수 응원 댓글 연동
  src/api/league-game/index.ts
  src/api/league-game/use-get-all-game-list.tsx
  src/api/league-game/use-get-game-by-league-game-id.tsx
  src/api/league-game/use-get-game-list-by-date.tsx
  src/api/league-game/use-get-game-list-by-league-game-id-year-month.tsx
  src/api/league-game/use-get-game-list-by-team-id.tsx
  src/api/player/index.ts
  src/api/player/players.ts
  src/api/player/use-get-all-player-list.tsx
  src/api/player/use-get-player-comment-list.tsx
  src/api/player/use-get-player.tsx
  src/api/player/use-write-player-comment.tsx
  src/app/(league)/premier/board/[postId]/page.tsx
  src/app/(league)/premier/write/page.tsx
  src/app/layout.tsx
  src/components/common/loading-spinner.tsx
  src/components/home/laliga-league-game.tsx
  src/components/home/premier-league-game.tsx
  src/components/league-game/date-picker.tsx
  src/components/league-game/league-game.tsx
  src/components/league-game/team-list.tsx
  src/components/league-game/team-logo.tsx
  src/components/match/match-record.tsx
  src/components/match/match.tsx
  src/components/player/player-career.tsx
  src/components/player/player-comment-item.tsx
  src/components/player/player-comment.tsx
  src/components/player/player-info-tab.tsx
  src/components/player/player-info.tsx
  src/components/player/player.tsx
  src/hooks/useInput.tsx
  src/types/players.ts
  src/utils/check-content.ts
  tailwind.config.ts
Labels: FEAT, REFACTOR, STYLE

#83 Feat/#71 팀별 일정 및 결과 조회
  src/api/league-game/league-games.ts
  src/api/league-game/use-get-game-list-by-team-id.tsx
  src/app/match/[leagueGameId]/page.tsx
  src/components/league-game/league-game-content-item.tsx
  src/components/league-game/league-game-content.tsx
  src/components/league-game/league-game.tsx
  src/components/league-game/service/game-list.ts
  src/components/league-game/team-list.tsx
  src/components/league-game/team-logo.tsx
  src/types/league-games.ts
Labels: FEAT, REFACTOR

#84 게시글 작성 api 변경
  src/api/post/posts.ts
  src/api/post/use-write-post.tsx
  src/app/(league)/premier/write/page.tsx
Labels: FIX

#85 게시글 수정 기능 추가
  src/api/post/index.ts
  src/api/post/posts.ts
  src/api/post/use-edit-post.tsx
  src/app/(league)/premier/board/[postId]/page.tsx
  src/app/(league)/premier/write/page.tsx
  src/components/board/post-edit-form.tsx
  src/components/write/post-form.tsx
  src/hooks/useInput.tsx
Labels: FEAT

#87 Fix: css className 수정
  src/app/globals.css
  src/app/layout.tsx
  tailwind.config.ts
Labels: FIX

#94 회원가입 기능 추가
  package-lock.json
  package.json
  src/api/auth/auths.ts
  src/api/auth/index.ts
  src/api/auth/use-signup.tsx
  src/app/signup/page.tsx
  src/components/auth-form/error-message.tsx
  src/components/auth-form/label.tsx
  src/components/common/button.tsx
  src/components/common/input.tsx
  src/constants/roles.ts
  src/types/auth.ts
Labels: FEAT

#96 Feat: 팀별 월별 경기 일정 api 연동, 구현
  src/api/league-game/league-games-types.ts
  src/api/league-game/league-games.ts
  src/api/league-game/use-get-game-by-league-game-id.tsx
  src/api/league-game/use-get-game-list-by-date.tsx
  src/api/league-game/use-get-game-list-by-league-game-id-year-month.tsx
  src/api/league-game/use-get-game-list-by-team-id.tsx
  src/api/league-game/use-get-game-list-by-team-year-month.tsx
  src/assets/img/logo/laliga_logo.png
  src/assets/img/logo/laliga_logo_small.png
  src/assets/img/logo/pl_logo.png
  src/assets/img/logo/pl_logo_small.png
  src/components/schedule/schedule.tsx
  src/components/schedule/service/game-list.ts
  src/components/schedule/team-list.tsx
  src/hooks/use-league-title.tsx
  src/types/leagues.ts
Labels: FEAT

#100 빌드 오류 수정
  src/app/page.tsx
  src/app/post/layout.tsx
  src/app/post/loading-dots.module.css
  src/app/post/loading.tsx
  src/app/post/page.tsx
  src/components/main-header/nav-link-item.tsx
  src/components/main-header/nav-link-list.tsx
Labels: FIX

#97 로그인, 인증, 로그아웃 기능 구현
  src/api/auth/auths.ts
  src/api/auth/index.ts
  src/api/auth/use-login.tsx
  src/api/intance.ts
  src/app/layout.tsx
  src/app/login/page.tsx
  src/components/common/input.tsx
  src/components/main-header/main-header.tsx
  src/constants/auth.ts
  src/contexts/auth-context.tsx
  src/hooks/use-auth-validation.tsx
  src/hooks/use-local-storage.tsx
  src/types/auth.ts
Labels: FEAT

#110 API 변경사항 반영
  src/api/post/posts.ts
  src/app/post/[postId]/page.tsx
  src/app/post/page.tsx
  src/components/post/post-item.tsx
  src/types/posts.ts
Labels: FEAT

#108 내 정보 페이지 추가
  src/api/member/index.ts
  src/api/member/members.ts
  src/api/member/use-get-member.tsx
  src/api/member/use-update-member.tsx
  src/api/member/use-update-password.tsx
  src/app/profile/page.tsx
  src/types/members.ts
Labels: FEAT

#114 Feat/#104 팀순위, 반응형 (새로운 풀리퀘)
  src/api/league/index.ts
  src/api/league/leagues.ts
  src/api/league/use-get-team-rank.tsx
  src/app/(league)/premier/schedule/match/[leagueGameId]/page.tsx
  src/app/login/page.tsx
  src/components/home/home-rank.tsx
  src/components/main-header/link-list-util.ts
  src/components/match/goal-Info.tsx
  src/components/match/match-header.tsx
  src/components/match/match-record-category-item.tsx
  src/components/match/match-record-tab.tsx
  src/components/match/match-record.tsx
  src/components/match/match-section.tsx
  src/components/match/match.tsx
  src/components/match/open-talk.tsx
  src/components/player-rank/player-rank-table.tsx
  src/components/player-rank/player-rank.tsx
  src/components/rank/rank-header.tsx
  src/components/rank/rank-item.tsx
  src/components/rank/rank-table.tsx
  src/components/rank/rank.tsx
  src/hooks/use-league-title.tsx
  src/types/leagues.ts
  src/utils/league-mapper.ts
Labels: FEAT, STYLE

#115 Feat/#111 경기 관련 api 변경사항 반영
  src/api/intance.ts
  src/components/match/match-header.tsx
  src/components/match/match.tsx
  src/components/schedule/schedule-content-item.tsx
  src/constants/league-game-id.ts
  src/types/schedules.ts
  src/utils/league-mapper.ts
Labels: FEAT

#116 Feat: 댓글 조회 구현
  src/api/comment/comments.ts
  src/api/comment/index.ts
  src/api/comment/use-get-comment-list.tsx
  src/app/post/[postId]/page.tsx
  src/components/post/comment-item.tsx
  src/components/post/comment-list.tsx
  src/types/comment.ts
Labels: FEAT

#117 토큰 초기화 이슈
  src/components/main-header/main-nav.tsx
  src/components/main-header/mobile-nav.tsx
  src/contexts/auth-context.tsx
  src/hooks/use-auth-validation.tsx
Labels: FIX

#119 Feat/#118 회원가입 반응형 구현
  src/api/intance.ts
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/components/common/container.tsx
Labels: FEAT, STYLE

#121 shadcn 초기설정
  components.json
  package-lock.json
  package.json
  src/app/globals.css
  src/components/home/home-post.tsx
  src/components/home/home-rank.tsx
  src/components/home/laliga-schedule.tsx
  src/components/home/premier-schedule.tsx
  src/components/main-header/modal-nav-link-list.tsx
  src/components/post/pagination.tsx
  src/utils/cn.ts
  tailwind.config.ts
Labels: FEAT

#124 profile-dropdown의 props 타입 이름을 ProfileDropdownProps로 수정
  src/components/main-header/profile-dropdown.tsx
Labels: FIX

#125 Feat/#122 시즌 변경 기능 추가, 경기 상세 정보 오류 수정
  src/components/match/match-record.tsx
  src/components/player-rank/player-rank.tsx
  src/components/rank/rank-header.tsx
  src/components/rank/rank.tsx
Labels: FEAT, FIX

#126 Feat/#123 헤더 구현, lint 오류 해결
  src/components/main-header/modal-nav-link-list.tsx
  src/components/main-header/nav-link-item.tsx
  src/components/ui/dropdown-menu.tsx
Labels: FEAT, FIX

#128 리액트 쿼리 queryClient 옵션 설정
  src/api/query-client.ts
  src/components/react-query-providers.tsx
Labels: FEAT

#131 Refactor/#130 헤더 nav 리팩토링
  src/app/profile/page.tsx
  src/components/main-header/main-header-nav.tsx
  src/components/main-header/main-header.tsx
  src/components/main-header/main-nav.tsx
  src/components/main-header/mobile-modal-nav-link-list.tsx
  src/components/main-header/mobile-modal-nav.tsx
  src/components/main-header/mobile-nav.tsx
  src/components/match/match-record.tsx
Labels: FIX, REFACTOR
